WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

CARD_WIDTH = 70
CARD_HEIGHT = 95

CARD_SHEET_TALL = 10
CARD_SHEET_WIDE = 6

CARDS_IN_SUIT = 13
CARDS_IN_DECK = 52

NUM_TABLEAUS = 7

-- starting indices for suits in sprite sheet
SPADES_START = 1
HEARTS_START = SPADES_START + CARDS_IN_SUIT + 1
DIAMONDS_START = HEARTS_START + CARDS_IN_SUIT
CLUBS_START = DIAMONDS_START + CARDS_IN_SUIT

-- default positions for faces in the sprite sheet
POS_A = 4
POS_2 = 13
POS_3 = 12
POS_4 = 11
POS_5 = 10
POS_6 = 9
POS_7 = 8
POS_8 = 7
POS_9 = 6
POS_10 = 5
POS_J = 3
POS_Q = 1
POS_K = 2

-- faces
ACE = 1
TWO = 2
THREE = 3
FOUR = 4
FIVE = 5
SIX = 6
SEVEN = 7
EIGHT = 8
NINE = 9
TEN = 10
JACK = 11
QUEEN = 12
KING = 13

-- suits
HEARTS = 'hearts'
DIAMONDS = 'diamonds'
CLUBS = 'clubs'
SPADES = 'spades'